In [1]:
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt
from IPython.display import HTML

from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [8]:
IMAGE_SIZE = 256
CHANNELS = 3

train_datagen = ImageDataGenerator(
    rescale=1./255,
    horizontal_flip=True,
    rotation_range=10
)

train_generator = train_datagen.flow_from_directory(
    'dataset/train',
    target_size=(IMAGE_SIZE,IMAGE_SIZE),
    batch_size=32,
    class_mode='sparse',
    save_to_dir='AugmentedImages'
)

Found 1506 images belonging to 3 classes.


In [9]:
for image_batch, label_batch in train_generator:
    print(image_batch[0])
    break

[[[0.7709317  0.7513239  0.76701015]
  [0.77484965 0.7552418  0.7709281 ]
  [0.7695797  0.74997187 0.76565814]
  ...
  [0.47064355 0.44319257 0.47064355]
  [0.47198954 0.44453853 0.47198954]
  [0.47333553 0.44588456 0.47333553]]

 [[0.77076346 0.75115556 0.7668419 ]
  [0.7746814  0.75507355 0.7707598 ]
  [0.77008444 0.7504766  0.7661629 ]
  ...
  [0.53144854 0.5039975  0.53144854]
  [0.5353182  0.5078672  0.5353182 ]
  [0.5391879  0.5117369  0.5391879 ]]

 [[0.7705952  0.75098735 0.7666736 ]
  [0.7745131  0.7549053  0.77059156]
  [0.77058923 0.7509814  0.76666766]
  ...
  [0.5156959  0.48824492 0.5156959 ]
  [0.5104802  0.48302925 0.5104802 ]
  [0.5052645  0.47781354 0.5052645 ]]

 ...

 [[0.63635904 0.6128296  0.62067276]
  [0.63484484 0.6113154  0.61915857]
  [0.6333306  0.6098012  0.6176443 ]
  ...
  [0.50980455 0.4705889  0.47451046]
  [0.51176804 0.47255233 0.4764739 ]
  [0.5137117  0.474496   0.47841758]]

 [[0.6400011  0.6164717  0.62431484]
  [0.64252484 0.6189954  0.62683856]


In [10]:
validation_datagen = ImageDataGenerator(
    rescale=1./255,
    horizontal_flip=True,
    rotation_range=10
)

validation_generator = validation_datagen.flow_from_directory(
    'dataset/val',
    target_size=(IMAGE_SIZE,IMAGE_SIZE),
    batch_size=32,
    class_mode='sparse',
    save_to_dir='AugmentedImages'
)

Found 215 images belonging to 3 classes.


In [11]:
test_datagen = ImageDataGenerator(
    rescale=1./255,
    horizontal_flip=True,
    rotation_range=10
)

test_generator = test_datagen.flow_from_directory(
    'dataset/test',
    target_size=(IMAGE_SIZE,IMAGE_SIZE),
    batch_size=32,
    class_mode='sparse',
    save_to_dir='AugmentedImages'
)

Found 431 images belonging to 3 classes.


In [16]:
input_shape = (IMAGE_SIZE, IMAGE_SIZE, CHANNELS)
n_classes = 3

model = models.Sequential([
    layers.InputLayer(input_shape=input_shape),
    layers.Conv2D(32, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(n_classes, activation='softmax')
])

In [17]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_18 (Conv2D)              │ (None, 254, 254, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_18 (MaxPooling2D) │ (None, 127, 127, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_19 (Conv2D)              │ (None, 125, 125, 64)   │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_19 (MaxPooling2D) │ (None, 62, 62, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_20 (Conv2D)              │ (None, 60, 60, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_20 (MaxPooling2D) │ (None, 30, 30, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_21 (Conv2D)              │ (None, 28, 28, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_21 (MaxPooling2D) │ (None, 14, 14, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_22 (Conv2D)              │ (None, 12, 12, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_22 (MaxPooling2D) │ (None, 6, 6, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_23 (Conv2D)              │ (None, 4, 4, 64)       │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_23 (MaxPooling2D) │ (None, 2, 2, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_3 (Flatten)             │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 64)             │        16,448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 3)              │           195 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 183,747 (717.76 KB)

 Trainable params: 183,747 (717.76 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=['accuracy'],
)

In [19]:
history = model.fit(
    train_generator,
    steps_per_epoch=47,
    batch_size=32,
    verbose=1,
    validation_data=validation_generator,
    validation_steps=6,
    epochs=20
)

Epoch 1/20


C:\Users\srawa\AppData\Roaming\Python\Python312\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:120: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


47/47 ━━━━━━━━━━━━━━━━━━━━ 84s 2s/step - accuracy: 0.4581 - loss: 0.9360 - val_accuracy: 0.4948 - val_loss: 0.8733
Epoch 2/20
 1/47 ━━━━━━━━━━━━━━━━━━━━ 26s 571ms/step - accuracy: 0.5000 - loss: 0.8573

c:\Program Files\Python312\Lib\contextlib.py:158: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self.gen.throw(value)


47/47 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.5000 - loss: 0.8573 - val_accuracy: 0.3478 - val_loss: 0.8621
Epoch 3/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 70s 1s/step - accuracy: 0.5818 - loss: 0.8050 - val_accuracy: 0.6615 - val_loss: 0.7466
Epoch 4/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.6562 - loss: 0.7148 - val_accuracy: 0.6087 - val_loss: 0.7903
Epoch 5/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 69s 1s/step - accuracy: 0.7043 - loss: 0.6428 - val_accuracy: 0.7500 - val_loss: 0.5509
Epoch 6/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.8750 - loss: 0.3904 - val_accuracy: 0.7826 - val_loss: 0.5834
Epoch 7/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 71s 1s/step - accuracy: 0.8415 - loss: 0.4209 - val_accuracy: 0.7708 - val_loss: 0.4322
Epoch 8/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.8750 - loss: 0.3333 - val_accuracy: 0.8261 - val_loss: 0.4237
Epoch 9/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 71s 1s/step - accuracy: 0.8252 - loss: 0.4163 - val_accuracy: 0.8542 - val_loss: 0.3141

In [20]:
scores = model.evaluate(test_generator)

C:\Users\srawa\AppData\Roaming\Python\Python312\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:120: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


14/14 ━━━━━━━━━━━━━━━━━━━━ 15s 1s/step - accuracy: 0.9192 - loss: 0.1772


In [21]:
scores

[0.18455778062343597, 0.9234338998794556]

In [24]:
model.save('../potatoes.h5')